name: Check LoL Patch
on:
  workflow_dispatch: # Se lance uniquement quand tu cliques sur "Run workflow"

jobs:
  send_patch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Configuration Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Installation des dépendances
        run: pip install requests
        
      - name: Envoi du Patch sur Discord
        run: python check_patch.py
