name: WoW Meta Bot

on:
  schedule:
    - cron: '0 */8 * * *'  # Toutes les 8 heures automatiquement
  workflow_dispatch:         # Permet de lancer manuellement aussi

jobs:
  send-meta:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installer les dépendances
        run: |
          pip install playwright requests
          playwright install chromium
          playwright install-deps chromium

      - name: Lancer DPS Bot
        run: python main.py

      - name: Lancer Healer Bot
        run: python heal.py

      - name: Lancer Tank Bot
        run: python tank.py
